copyright: Copyright &copy; 2020-2024
dev_addr: 127.0.0.1:8001
docs_dir: docs/src
edit_uri: 'blob/develop/docs/'
repo_url: https://github.com/pytest-dev/pytest-echo
site_author: Stefano Apostolico
site_description: ""
site_dir: ./~build/docs
site_name: pytest-echo
site_url: https://pytest-dev.github.io/pytest-dev/pytest-echo/
strict: false
exclude_docs: |
  _docs/*
  _hooks/*
  _includes/*
  _scripts/*
  ~*

markdown_extensions:
  - admonition
  - pymdownx.magiclink

theme:
  name: "material"
  color_mode: auto
  user_color_mode_toggle: true
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohidex
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  extra:
    version:
      provider: mike
      alias: true

plugins:
#  - mkdocstrings:
#      default_handler: python
  - awesome-pages
  - search

watch:
  - src/
